// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAU3-DDvx8jugkAim2N08g2gfxYe-Llirs',
    appId: '1:243632737581:web:20fa7ee6307750c9c297a4',
    messagingSenderId: '243632737581',
    projectId: 'gymtrack-987f6',
    authDomain: 'gymtrack-987f6.firebaseapp.com',
    storageBucket: 'gymtrack-987f6.firebasestorage.app',
    measurementId: 'G-WH51QQXYR3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrtlqwEcUf6I16Hoa4SUYAwhfH-hlgmUQ',
    appId: '1:243632737581:android:d91873f1e5b07b29c297a4',
    messagingSenderId: '243632737581',
    projectId: 'gymtrack-987f6',
    storageBucket: 'gymtrack-987f6.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmOen7uaPInD5RDa8zLBtHODLV749mbaA',
    appId: '1:243632737581:ios:b59695460bc3f6f6c297a4',
    messagingSenderId: '243632737581',
    projectId: 'gymtrack-987f6',
    storageBucket: 'gymtrack-987f6.firebasestorage.app',
    iosBundleId: 'com.example.gymtrack',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmOen7uaPInD5RDa8zLBtHODLV749mbaA',
    appId: '1:243632737581:ios:b59695460bc3f6f6c297a4',
    messagingSenderId: '243632737581',
    projectId: 'gymtrack-987f6',
    storageBucket: 'gymtrack-987f6.firebasestorage.app',
    iosBundleId: 'com.example.gymtrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAU3-DDvx8jugkAim2N08g2gfxYe-Llirs',
    appId: '1:243632737581:web:3aa6b6ca43620692c297a4',
    messagingSenderId: '243632737581',
    projectId: 'gymtrack-987f6',
    authDomain: 'gymtrack-987f6.firebaseapp.com',
    storageBucket: 'gymtrack-987f6.firebasestorage.app',
    measurementId: 'G-XZXZDMP73V',
  );
}
